package test

import (
	"context"
	"crypto/rand"
	"fmt"
	"math/big"

	"github.com/docker/docker/api/types/container"
	"github.com/docker/go-units"
	"github.com/testcontainers/testcontainers-go"
	"github.com/testcontainers/testcontainers-go/modules/mongodb"
	"github.com/testcontainers/testcontainers-go/wait"
)

// StartMongoContainer creates and starts an instance of the mongodb container
// The caller is responsible for terminating the container.
func StartMongoContainer(ctx context.Context) (*mongodb.MongoDBContainer, error) {
	opts := []testcontainers.ContainerCustomizer{
		testcontainers.WithWaitStrategy(
			wait.ForAll(
				wait.ForLog("Waiting for connections"),
				wait.ForListeningPort("27017/tcp"),
			),
		),
		// avoid `error in creating eventfd: Too many open files, errno: 24`
		testcontainers.WithHostConfigModifier(func(hc *container.HostConfig) {
			hc.Ulimits = []*units.Ulimit{
				{
					Name: "nofile",
					Hard: 65536, // Maximum file descriptors
					Soft: 65536, // Current limit
				},
			}
		}),
	}

	mongodbContainer, err := mongodb.Run(ctx, "mongo:7", opts...)
	if err != nil {
		return nil, fmt.Errorf("failed to start container: %w", err)
	}
	return mongodbContainer, nil
}

//
// Copy-pasted verbatim from github.com/strikesecurity/strikememongo
//

// DBNameLen is the length of a database name generated by RandomDatabase().
// It's OK to change this, but not concurrently with calls to RandomDatabase.
const DBNameLen = 15

// DBNameChars is the set of characters used by RandomDatabase().
// It's OK to change this, but not concurrently with calls to RandomDatabase.
const DBNameChars = "abcdefghijklmnopqrstuvwxyz"

// RandomDatabaseName returns a random valid mongo database name. You can use to
// to pick a new database name for each test to isolate tests from each other
// without having to tear down the whole server.
//
// This function will panic if it cannot generate a random number.
func RandomDatabaseName() string {
	dbChars := make([]byte, DBNameLen)
	for i := 0; i < DBNameLen; i++ {
		bigN, err := rand.Int(rand.Reader, big.NewInt(int64(len(DBNameChars))))
		if err != nil {
			panic(fmt.Errorf("error getting a random int: %s", err))
		}

		dbChars[i] = DBNameChars[int(bigN.Int64())]
	}

	return string(dbChars)
}
