version: "2"
linters:
  enable:
    - goconst
    - lll
    - misspell
    - revive
  settings:
    lll:
      line-length: 130
    revive:
      enable-all-rules: true
      rules:
      - name: line-length-limit # lll is already run by golangci-lint
        disabled: true
      - name: function-length # test funcs are usually long and complex, and that's ok
        exclude: ["**/*_test.go"]
      - name: cognitive-complexity # test funcs are usually long and complex, and that's ok
        exclude: ["**/*_test.go"]
      - name: cyclomatic # test funcs are usually long and complex, and that's ok
        exclude: ["**/*_test.go"]
        # Disable some rules until fixing the issues in current codebase
      - name: exported # TODO: fix all issues and re-enable this rule
        disabled: true
      - name: use-errors-new # TODO: fix all issues and re-enable this rule
        disabled: true
      - name: add-constant # TODO: fix all issues and re-enable this rule
        disabled: true
      - name: cyclomatic # TODO: fix all issues and re-enable this rule
        disabled: true
      - name: cognitive-complexity # TODO: fix all issues and re-enable this rule
        disabled: true
      - name: function-length # TODO: fix all issues and re-enable this rule
        disabled: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
formatters:
  enable:
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
