name: saas-backend

services:
  api:
    platform: linux/amd64
    env_file:
      - .env
    environment:
      - VOCDONI_MONGOURL=mongodb://root:vocdoni@mongo:27017/?replicaSet=rs0
    build:
      context: ./
    ports:
      - ${VOCDONI_PORT}:${VOCDONI_PORT}
    sysctls:
      net.core.somaxconn: 8128
    restart: ${RESTART:-unless-stopped}
    depends_on: 
      - mongo

  mongo:
    image: mongo
    restart: ${RESTART:-unless-stopped}
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=vocdoni
      - MONGO_INITDB_DATABASE=saasdb
    command: ["--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongodb:/data/mongodb
      - ./scripts/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro

  mongo-express:
    image: mongo-express
    restart: ${RESTART:-unless-stopped}
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: vocdoni
      ME_CONFIG_MONGODB_URL: mongodb://root:vocdoni@mongo:27017/?replicaSet=rs0

volumes:
  mongodb: {}
